---
title: Home
---

* Zhuyang Wang

- Advisor: [[http://jhc.sjtu.edu.cn/staffInfo/23/][Prof. Qinxiang Cao]]
- Github: [[https://github.com/hawnzug][hawnzug]]
- Twitter: [[https://twitter.com/hawnzug][@hawnzug]]
- Email: [[mailto:wzy1997@sjtu.edu.cn][wzy1997@sjtu.edu.cn]] | [[mailto:hawnzug@gmail.com][hawnzug@gmail.com]] 
- IRC: Sometimes you can find me on =freenode= as =hawnzug=

I am an undergraduate majoring in Computer Science at [[https://www.sjtu.edu.cn/][Shanghai Jiao Tong
University]].  I am interested in Functional Programming and Programming Language.
I am also a proud member of [[http://sjtug.org][SJTUG]], a joyful Linux user group.  My favorite
programming languages are Haskell, Agda and Coq.

I have been using Arch Linux on my laptop for several years and it works well.
I enjoy editting in Vim, but now I switch to Emacs equipped with Evil.

Name is an indispensable part of any formal languages, as well as in natural
language. Since Chinese naming convention has subtle differences with English, I
will explain this a bit more here.  My name in Chinese is 王竹阳, composed of
three characters 王(Wang), 竹(Zhu) and 阳(Yang). Those characters means king,
bamboo and sun respectively, and you may pronounce my name like wong-drew-young
in English.  The surname is 王, the given name is 竹阳. There is no middle name
in Chinese so 竹 is not my middle name.  You can see that first name and last
name are reversed in Chinese name in contrast to English name.

This site is written in [[https://orgmode.org/][Org mode]] and generated by [[https://jaspervdj.be/hakyll/][Hakyll]]. Because I had some
awful experiences writing CSS, I keep as little CSS as possible, except some
basic settings for readability and some generated by [[https://pandoc.org/][Pandoc]] for syntax
highlighting. So the whole site is almost plain HTML and I never had to worry
about choosing a theme.
